version: '3.1'

services:
  postgresqldb:
    image: postgres
    ports:
      - "5105:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres_java